removed every mention of angstrom, fixes issue #14
JuliaAstro/UnitfulAstro.jl pull request #15
Opened 2019-12-07 21:22 UTC by xzackli

As described in #14, Unitful.jl now has an angstrom unit, so we should remove it from this package to avoid annoying warnings when using the two together. As you can see from the diffs, I just typed `rg -i angstrom` and removed every line with a mention of it.

2019-12-08 10:59 UTC, giordano requested changes
Thank you so much!  In addition to the comments below, you need to bump the required version of Unitful to 0.18

2019-12-08 10:59 UTC, giordano commented on NEWS.md
> +* List of units: erg, dyn, arcmin, arcsec, Julian year, AU, light year, parsec, Jansky,
This was good, it's part of the documentation :wink:

2019-12-08 10:59 UTC, giordano commented on test/runtests.jl
> -        @test 1*u.angstrom == 1e-10*u.m
The unit is no more defined by this package, nevertheless I think we may want to be sure it's available, as it's important for astronomical applications.

2019-12-18 16:34 UTC, xzackli commented on NEWS.md
> +* List of units: erg, dyn, arcmin, arcsec, Julian year, AU, light year, parsec, Jansky,
Wow, that's embarrassing! You can tell that I really did just search for every mention of angstrom and remove it, hehe.

2019-12-18 16:39 UTC, xzackli commented
I've committed the requested changes, sorry it took a bit (end of semester, had to give a final and grade it).

2019-12-18 17:38 UTC, xzackli commented
The angstrom test fails for the appveyor 32-bit Windows build. Could it be that the rational number type (which I assume is made of two ints) defining the angstrom in [Unitful](https://github.com/PainterQubits/Unitful.jl/blob/master/src/pkgdefaults.jl#L185) in relation to the meter involves a factor of 10^10, which exceeds 2^31?

2020-01-02 23:03 UTC, giordano commented on Project.toml
> +Unitful = "≥ 0.18.0"
```suggestion
Unitful = "0.18.0"
```

2020-01-02 23:03 UTC, giordano commented on Project.toml
>  julia = "≥ 1.0.0"
```suggestion
julia = "1.0.0"
```

2020-01-02 23:58 UTC, giordano approved these changes

2020-01-03 00:15 UTC, merged

2020-01-03 00:15 UTC, giordano commented
Thank you so much and sorry for the late review!